modLoader = "javafml"
loaderVersion = "[35,)"
issueTrackerURL = "https://github.com/UnRealDinnerbone/JAMD2/issues"
license = "All Rights Reserved unless stated otherwise. Distrubtion permssion is given to FeedTheBeast and CurseForge for use in modpacks"

[[mods]]
modId = "jamd"
version = "${version}"
displayName = "Just Another Mining Dimesnion"
authors = "UnRealDinnerbone"
description = '''
A Mining Dimesnion Mod now for Forge and Fabric
'''
logoFile = "icon.png"

[[dependencies.jamd]]
modId = "forge"
mandatory = true
versionRange = "[35,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.jamd]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.jamd]]
modId = "architectury"
mandatory = true
versionRange = "[1.1.55,)"
ordering = "AFTER"
side = "BOTH"